version: '3.7'

services:
  cgm-ack:
    container_name: cgm-ack
    build: .
    image: jonheese/cgm-ack:latest
    volumes:
      - type: bind
        source: ./config.json
        target: /usr/src/app/config.json
    ports:
      - "127.0.0.1:5003:5003"
    restart: always
